Fix open-source build
cl/477725360 broke the open-source build, for example in Chromium

net/third_party/quiche/src/quiche/quic/core/quic_dispatcher_test.cc:2298:30: error: no member named 'UnconditionallyAddNewConnectionIdForTest' in 'quic::test::(anonymous namespace)::MockServerConnection'
    mock_server_connection1->UnconditionallyAddNewConnectionIdForTest(
    ~~~~~~~~~~~~~~~~~~~~~~~  ^

PiperOrigin-RevId: 478466288