Move balsa_fuzz_util to a separate quiche_fuzz_support glob.
While rolling QUICHE to Chromium (https://chromium-review.googlesource.com/c/chromium/src/+/7305931), if quiche_test_support depends on fuzztest (which is needed because quiche_test_support now builds balsa_fuzz_util.*), it throws the following error:

```
lld-link: error: duplicate symbol: LLVMFuzzerCustomMutator
>>> defined at obj/content/test/fuzzer/first_party_set_parser_json_fuzzer/first_party_set_parser_json_fuzzer.obj
>>> defined at obj/third_party/fuzztest/fuzztest/compatibility_mode.obj
```

This change separates balsa_fuzz_util.* to a new filelist so that we can build it separately and add the fuzztest dependency just where it is needed, to avoid having the fuzztest dependency for all of quiche_test_support.

PiperOrigin-RevId: 848182347