Avoid tripping -Wchanges-meaning in GCC
I got this warning building QUICHE with GCC because I forgot to `CC=clang`:

```
quiche/quic/core/qpack/qpack_encoder_stream_sender_test.cc:28:19: error: declaration of 'quic::HuffmanEncoding quic::test::{anonymous}::QpackEncoderStreamSenderTest::HuffmanEncoding()' changes meaning of 'HuffmanEncoding' [-Wchanges-meaning]
   28 |   HuffmanEncoding HuffmanEncoding() {
      |                   ^~~~~~~~~~~~~~~
quiche/quic/core/qpack/qpack_encoder_stream_sender_test.cc:28:3: note: used here to mean 'enum class quic::HuffmanEncoding'
   28 |   HuffmanEncoding HuffmanEncoding() {
      |   ^~~~~~~~~~~~~~~
```

The fix is easy enough.

PiperOrigin-RevId: 698519906