Add two missing includes to unblock QUICHE roll to Chromium.
Rolling is currently blocked by the following compilation errors:
  error: no member named 'HexStringToBytes' in namespace 'absl'
  error: no member named 'list' in namespace 'std'

PiperOrigin-RevId: 370900743
Change-Id: I3d610793a8ce304da27a84c2b0dc7850c93024ec