Fix open-source build
cl/477725360 broke the open-source build, for example in Envoy

external/com_github_google_quiche/quiche/quic/core/quic_dispatcher.cc:1111:23: error: use of undeclared identifier 'session'; did you mean 'session2'?
      if (session2 == session || cid == server_connection_id) {

PiperOrigin-RevId: 478109222