Move const declarations into quic_stream_sequencer_buffer.cc
constexpr members of a class require definition in addition to declaration and initialization.
In Chromium, it is a link error:
error: undefined symbol: quic::QuicStreamSequencerBuffer::kInitialBlockCount
>>> referenced by quic_stream_sequencer_buffer.cc:88 (../../net/third_party/quiche/src/quic/core/quic_stream_sequencer_buffer.cc:88)
>>>               obj/net/third_party/quiche/quiche/quic_stream_sequencer_buffer.o:(quic::QuicStreamSequencerBuffer::MaybeAddMoreBlocks(unsigned long))
clang: error: linker command failed with exit code 1 (use -v to see invocation)

kInitialBlockCount, kBlocksGrowthFactor are only used in .cc file.

PiperOrigin-RevId: 341931802
Change-Id: Ie0dfb5d4f777bdcb68ce9cf7327d589d58dd64ff