Remove a stray semi-colon from quiche_protocol_flags_list.h
A stray semi-colon in quiche_protocol_flags_list.h causes the following error when compiling Chromium:
```
In file included from ../../net/third_party/quiche/src/quiche/common/platform/default/quiche_platform_impl/quiche_flags_impl.cc:5:
In file included from ../../net/third_party/quiche/src/quiche/common/platform/default/quiche_platform_impl/quiche_flags_impl.h:24:
../../net/third_party/quiche/src/quiche/common/quiche_protocol_flags_list.h:281:69: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
  281 |     "Alarm update granularity used by the QUICHE multiplexer alarm");
```

Remove it.

No functional change.

PiperOrigin-RevId: 692059860