Use the right SetFlag() function in TlsClientHandshakerTest
This blocks rolling quiche to Chromium as compiling caused the following errors:
- error: no member named 'SetFlag' in namespace 'absl'
- error: use of undeclared identifier 'FLAGS_gfe2_reloadable_flag_quic_gfe_allow_alps_new_codepoint'

PiperOrigin-RevId: 587934731