Add missing dependency to quiche_test_support
The build currently fails with the following error:

```
quiche/quic/test_tools/quic_connection_peer.cc:12:10: error: module //quiche:quiche_test_support does not depend on a module exporting 'absl/types/variant.h'
#include "absl/types/variant.h"
         ^
```

PiperOrigin-RevId: 696162022