Automated g4 rollback of changelist 449982178.
*** Reason for rollback ***

We've figured out how to make this work in Envoy.

*** Original change description ***

Automated g4 rollback of changelist 449624054.

*** Reason for rollback ***

This CL breaks Envoy:

ERROR: /usr/local/google/home/rch/.cache/bazel/_bazel_rch/1bcaf4376ad2a122efbb41b7f1024923/external/com_github_google_quiche/BUILD.bazel:239:22: Label '@com_github_google_quiche//:quiche/http2/adapter/mock_http2_visitor.h' is invalid because '@com_github_google_quiche//quiche' is a subpackage; perhaps you meant to put the colon here: '@com_github_google_quiche//quiche:http2/adapter/mock_http2_visi...

***

PiperOrigin-RevId: 450749239